### PR TITLE
First commit for the text classification notebook

### PR DESCRIPTION
**Pull request by joaq-rod**
This notebook is a simplified version of [this one](https://github.com/kluster-ai/klusterai-cookbook/blob/main/examples/multiple-tasks-batch-api.ipynb), where only one task is performed.

### CODE REVIEW

**Comment by rymc** [comment]
Looks good but some suggestions that might make it even clearer:

1) use `pip install -q openai` to reduce the amount of amount
2) can we remove the use of JSON entirely for this version? It will simplify the prompt and results, reduce code, and keep the focus on the higher level steps.
3) do we need a task_type given there is only one task?
4) can we replace "predictions" with "inference"?
5) "Welcome to the text classification notebook with kluster.ai Batch API!" -> "with the kluster.ai"
6) I am not sure inputting the API key should be considered a task.
7) "Run the Classification Process" -> "perform a classification task using a state-of-the-art LLM".
8) "(make sure it has no blank spaces)" is repeated
9) can you double check all the imports are required?
10) after the JSONL file is created, it would be good to print it out and show what it looks like to help the user understand.

**Comment by joaq-rod** [comment]
I addressed all of what you suggested in this PR and in our chat (rename "task" to "request" everywhere)

**Comment by joaq-rod** [comment]
Here are some more requests from Ryan:
- "From a few entries to thousands.": Why thousands?

- "create_request" & "save_request": Should these be "job" instead of "request"? Same with the filename.

- "request_list[0]": Instead of this, can we do `!head -n 20 filename.csv` and show the actual file? 

- "Upload batch file to kluster.ai": Should this be broken out into two steps: the first uploads the file, and the next cell starts the batch job? 

- "Get the results":
  - Can you write a few lines here that explain what is going on?
  - I would also suggest making this part more simple, maybe just showing the output of:
    `result = client.files.content(result_file_id).content`

**Comment by m00nl1ghtP00l** [comment]
my comments
0/ This notebook showcases how to use the <a href="https://kluster.ai/" target="_blank">kluster.ai</a> batch API to classify movies into predefined categories based on their descriptions. With a user-friendly approach, you can effortlessly process datasets of any scale, from small collections to extensive datasets, and obtain categorized results powered by a state-of-the-art language model. 
-> This notebook showcases how to use the kluster.ai batch API to classify a data set based on a predefined set of categories. In our example, we use an extract from the IMDB top 1000 movies dataset and categorize them into one of “Action”, “Adventure”, “Comedy”, “Crime”, “Documentary”, “Drama”, “Fantasy”, “Horror”, “Romance”, or “Sci-Fi”. We are using a movies dataset but you can adapt this example by using your data and categories relevant for your use case. With this approach, you can effortlessly process datasets of any scale, from small collections to extensive datasets, and obtain categorized results powered by a state-of-the-art language model. 
1/ we need to align with Anjin on the launch of the new terminology Adaptive Inference  i.e are we ok to publish this as Batch API or do we have to update all notebooks with Adaptive Inference? My preference is to publish what we have an update the copy but let's get Anjin's feedback. 
2/ Note: you may need to restart the kernel to use updated packages. -> Note: you may need to restart the runtime to use updated packages.
3/ Sentence case Create a Batch File (and same for steps 2 and 3)-> Create a batch file (or maybe Create an adaptive inference file TBD)
4/ With the file successfully uploaded, we’re ready to start the batch job. -> Once the file has been successfully uploaded, we’re ready to start the batch job.
5/ The batch job has been created, and the request is now being processed! In the following section, we’ll monitor the status of the job to see how it's progressing. Let’s take a look and keep track of it's completion. -> Now that the batch job has been created, your request is now being processed! In the following section, we’ll monitor the status of the job to see how it's progressing. Let’s take a look and keep track of it's status.
6/ **REMEMBER:** The time to complete a batch inference job can take up to 24 hours. Although, it typically completes in much less time. -> I think we should say this in the previous "Start the job" section. 
7/ In the "Get the results" section there is a spurious "results" parameter on the last line. 
8/ The output object is hard to read. Suggest you show this in a human readable format.

**Comment by joaq-rod** [comment]
I’ve addressed your comments, Eric.
- I also changed every instance of ‘BATCH’ to ‘Adaptive Inference’ or ‘inference’ (depending on the case).
- 2/ This is the direct output of the pip code.
- 8/ Ryan suggested this, so I left it as he asked.

**Comment by rymc** [comment]
I suggest to merge it. 

I then suggest in  the next version we can take Erics feedback into account and pretty print / extract the label as the final step.

**Comment by m00nl1ghtP00l** [comment]
We agreed today to not update the terminology to Adaptive Inference until the website goes live for the reason that we are treating the website as a test - we may change Adaptive Inference if we do not receive a string signal from the market. So in the interest of staying agile, we should decouple the Adaptive inference changes until we get an "ok" from Anjin

**Review by m00nl1ghtP00l — COMMENTED** [review]
We agreed today to not update the terminology to Adaptive Inference until the website goes live for the reason that we are treating the website as a test - we may change Adaptive Inference if we do not receive a string signal from the market. So in the interest of staying agile, we should decouple the Adaptive inference changes with the overall improvements to the Notebook. 
Let's only add Adaptive Inference when we get an "ok" from Anjin

**Pull request merged**
