### PR TITLE
Add new notebook that follows getting started guide

### PR DESCRIPTION
**Pull request by joaq-rod**

### CODE REVIEW

**Comment by joaq-rod** [comment]
I added a small modification to the multiple-tasks-batch-api.ipynb in the Check Job code to adapt to the upcoming changes with lowercase status names.

**Comment by joaq-rod** [comment]
Re-wrote every 'canceling' and 'canceled' to 'cancelling' and 'cancelled' respectively

**Comment by rymc** [comment]
Good observation on the "cancelling" difference! 

Some other feedback on the notebook:

>Getting Started with the kluster.ai Batch Prediction API

I wouldn’t use the terminology of “Prediction”. LLMs also do generation (such as in this colab example where it is explaining a theory). How about “Getting Started with the kluster.ai Batch Job API for LLM Inference”

> Learn how to set up and configure the API.

I find the "configure the API" a bit confusing. How about "Learn how to use the kluster.ai API"?

> See how to submit batch prediction requests.

As with the first comment, our API does a lot more than prediction. I would say something like “Submit a simple batch job for LLM inference”

> Creating Batch Jobs as JSON Files  

This should be JSONL files

> Uploading Batch job files 

files -> Files 

> This step defines a batch of tasks for the API to process. Each task includes a unique identifier,

I think we should use “requests” instead of tasks.

>  the model to use, and input prompts. These tasks are saved as a JSON Lines (.jsonl) file for efficient handling of multiple requests in a single upload.

I don’t think “input prompts” is technically correct. How about something like “Each request includes unique identifier (“custom_id”) , the HTTP method (“POST”),  the chat completions endpoint (“/v1/chat/completions”) and a body field that contains a request you would send to the chat completions endpoint, including the “model” to use, and the conversational context (“messages”).


> This step uploads the input file for your batch job. The API stores it and returns a file ID to use in the next steps, preparing your data for processing.  

How about adding a little more, something like how the API uploads the JSONL file to kluster.ai and then provides you with a unique id for that file, and that id is used when you want a batch job to use that file. 

>Submit your Batch job 

job -> Job  

>This step lists the most recent batch jobs, providing an overview of their statuses and details  

This sentence is missing a full stop.


>This step retrieves a list of available models, providing details about each model you can use for your tasks. 
Tasks is a little ambiguous here, I think requests is better.


> client.batches.cancel("mybatch-123") # Replace with your batch id 

Given this is a colab notebook, can we make the code executable, e.g., replacing this string with an actual variable? 

Along the same lines, how about only creating the openai client once at the start, and then reusing it throughout. I think in one regard this is the difference between API docs and a colab, the API docs may be used in isolation (i.e., someone searched and went straight to the list models endpoint, so having the client  code there is useful, but for colab they would execute all the code and understand the flow as one.

**Comment by m00nl1ghtP00l** [comment]
My comments:
1. To be consistent with the existing docs let's use "Batch API" instead of "Batch Prediction API"
2. "- See how to submit batch prediction requests." -> "- See how to submit batch requests."
3. "This step ensures that the openai Python library is installed or updated to the required version. This library will serve as the client for interacting with the kluster.ai Batch Prediction API." -> "[...] kluster.ai Batch API."
4. "You'll have to enter your personal kluster.ai API key (make sure it has no blank spaces). Remember to <a href="https://platform.kluster.ai/signup" target="_blank">sign up</a> if you don't have one yet." -> "You'll have to enter your kluster.ai API key (make sure it has no blank spaces). Remember to create a key in platform.kluster.ai, if you don't have one yet. " . I am assuming that if the user gets to this notebook they are probably linking to it from the webapp so already have signed up.
5."This step lists the most recent batch jobs, providing an overview of their statuses and details" -> "This step lists your batch jobs, providing an overview of their statuses and details. To constrain the query response, use the limit parameter.".
6. "This step cancels an ongoing batch job using its batch ID, stopping further processing." -> "To cancel a batch job that is currently in progress, invoke the batch cancel endpoint by providing the batch ID".

**Pull request merged**
